// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwP0Cs4--QFDI4KwmbGSkEGRbhRiYnEK4',
    appId: '1:137591066546:web:407c8ec52c0e1af4a51eab',
    messagingSenderId: '137591066546',
    projectId: 'nirvaaki',
    authDomain: 'nirvaaki.firebaseapp.com',
    storageBucket: 'nirvaaki.appspot.com',
    measurementId: 'G-FSZ2HD6H16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNzpPciGY_JD5MkIhp5sRYzgJz1xXndl4',
    appId: '1:137591066546:android:fca20b325465e7bda51eab',
    messagingSenderId: '137591066546',
    projectId: 'nirvaaki',
    storageBucket: 'nirvaaki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPThdonx48Fx-6nYNEQNpMMZNZWHsB-ls',
    appId: '1:137591066546:ios:3c761822738fa1d4a51eab',
    messagingSenderId: '137591066546',
    projectId: 'nirvaaki',
    storageBucket: 'nirvaaki.appspot.com',
    iosBundleId: 'com.appwise.yesBrokr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPThdonx48Fx-6nYNEQNpMMZNZWHsB-ls',
    appId: '1:137591066546:ios:30db61557d56e3e7a51eab',
    messagingSenderId: '137591066546',
    projectId: 'nirvaaki',
    storageBucket: 'nirvaaki.appspot.com',
    iosBundleId: 'com.example.yesBroker.RunnerTests',
  );
}
